name: Build and Release BHTwitter

on:
  workflow_dispatch:
    inputs:
      decrypted_twitter_url:
        description: "The direct URL to the decrypted Twitter ipa"
        default: ""
        required: true
        type: string
      commit_id:
        description: "(Optional) Commit ID to build at"
        default: ""
        required: false
        type: string
      create_release:
        description: "Create a draft release"
        default: true
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build BHTwitter
    runs-on: macos-12
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.6
        with:
          path: main
          ref: ${{ github.event.inputs.commit_id || github.ref }}
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Setup Theos
        uses: actions/checkout@v4.1.6
        with:
          repository: theos/theos
          ref: 3da31488281ecf4394d10302d2629607f4a1aa07
          path: theos
          submodules: recursive

      - name: Caching
        id: SDK
        uses: actions/cache@v4.0.2
        env:
          cache-name: iOS-16.4-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}

      - name: Download iOS 16.4 SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          git clone -n --depth=1 --filter=tree:0 https://github.com/arichorn/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.4.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.1.6
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive
        
      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Prepare Twitter iPA
        run: |
          wget "$TWITTER_URL" --no-verbose -O main/Twitter.ipa
          unzip -q main/Twitter.ipa -d main/tmp
          echo "TWITTER_VERSION=$(grep -A 1 '<key>CFBundleVersion</key>' main/tmp/Payload/Twitter.app/Info.plist | grep '<string>' | awk -F'[><]' '{print $3}')" >> $GITHUB_ENV
          rm -rf main/tmp/Payload/Twitter.app/_CodeSignature/CodeResources
          rm -rf main/tmp/Payload/Twitter.app/PlugIns/*
          if [ -d "main/Extensions" ]; then
            cp -R main/Extensions/*.appex main/tmp/Payload/Twitter.app/PlugIns
          fi
        env:
          THEOS: ${{ github.workspace }}/theos
          TWITTER_URL: ${{ inputs.decrypted_twitter_url }}

      - name: Fix Compiling & Build Package
        id: build_package
        run: |
          (echo export PATH="/usr/local/opt/make/libexec/gnubin:$PATH" >> ~/.bash_profile)
          source ~/.bash_profile
          cd ${{ github.workspace }}/main
          chmod +x ./build.sh
          ./build.sh --sideloaded
          OUTPUT_FILE=$(ls -t packages | head -n1)
          mv "packages/$OUTPUT_FILE" "packages/BHTwitter-sideloaded_${{ env.TWITTER_VERSION }}.ipa"
          echo "package=$(ls -t packages | head -n1)" >> $GITHUB_OUTPUT
          echo -e "==> \033[1mSHASUM256: $(shasum -a 256 packages/*.ipa | cut -f1 -d' ')\033[0m"
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Verify Package
        run: |
          ls -lh main/packages/
          FILE_PATH="main/packages/BHTwitter-sideloaded_${{ env.TWITTER_VERSION }}.ipa"
          if [ ! -f "$FILE_PATH" ]; then
            echo "File not found: $FILE_PATH"
            exit 1
          fi
          if [ ! -s "$FILE_PATH" ]; then
            echo "File is empty: $FILE_PATH"
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: BHTwitter-sideloaded_${{ env.TWITTER_VERSION }}
          path: ${{ github.workspace }}/main/packages/BHTwitter-sideloaded_${{ env.TWITTER_VERSION }}.ipa
          if-no-files-found: error
      
      - name: Prepare Release Notes
        run: |
          export TODAY=$(date '+%Y-%m-%d')
          echo -e "## Release Notes\n\n**Build Option:** Sideloaded\n**Twitter Version:** ${{ env.TWITTER_VERSION }}\n**Date:** $TODAY\n\n- Built using BHTwitter project." > ${{ github.workspace }}/release_notes.md

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT: ${{ inputs.create_release }}
        with:
          tag_name: v${{ env.TWITTER_VERSION }}-sideloaded
          name: v${{ env.TWITTER_VERSION }}-sideloaded - BHTwitter
          files: main/packages/BHTwitter-sideloaded_${{ env.TWITTER_VERSION }}.ipa
          draft: ${{ env.DRAFT }}
          body_path: ${{ github.workspace }}/release_notes.md

      - name: Update Altstore Source with latest release
        run: |
          curl --location --request POST 'https://api.github.com/repos/BandarHL/BHTwitterAltstore/dispatches' \
          --header 'Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "event_type": "update-altstore-source-trigger"
          }'
