name: Build and Release BHTwitter

on:
  workflow_dispatch:
    inputs:
      decrypted_twitter_url:
        description: "The direct URL to the decrypted Twitter ipa"
        default: ""
        required: true
        type: string
      commit_id:
        description: "(Optional) Commit ID to build at"
        default: ""
        required: false
        type: string
      create_release:
        description: "Create a draft release"
        default: true
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build BHTwitter
    runs-on: macos-12
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          path: main
          ref: ${{ github.event.inputs.commit_id || github.ref }}
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ${{ github.workspace }}/theos
          echo "export THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV
          echo "export THEOS_MAKE_PATH=${{ github.workspace }}/theos/makefiles" >> $GITHUB_ENV

      - name: Caching
        id: SDK
        uses: actions/cache@v4
        env:
          cache-name: iOS-16.4-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}

      - name: Download iOS 16.4 SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          git clone -n --depth=1 --filter=tree:0 https://github.com/arichorn/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.4.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Setup Theos Jailed
        uses: actions/checkout@v4
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive
        
      - name: Set PATH environment variable
        run: echo "export PATH=\$PATH:${{ github.workspace }}/theos:${{ github.workspace }}/theos-jailed" >> $GITHUB_ENV

      - name: Export decrypted twitter ipa
        run: |
          cd main
          mkdir -p packages
          curl "${{ github.event.inputs.decrypted_twitter_url }}" -o packages/com.atebits.Tweetie2.ipa
          ls -lh packages
          ls -lh packages/com.atebits.Tweetie2.ipa

      - name: Build and Package
        run: |
          cd main
          chmod +x build.sh
          ./build.sh --sideloaded
        env:
          THEOS: ${{ github.workspace }}/theos
          THEOS_MAKE_PATH: ${{ github.workspace }}/theos/makefiles

      - name: Check for IPA File
        run: |
          cd main/packages
          if [ -f "BHTwitter-sideloaded.ipa" ]; then
            echo "IPA file exists."
          else
            echo "IPA file not found!"
            exit 1
          fi

      - name: Create GitHub Release
        if: ${{ github.event.inputs.create_release }}
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.event.inputs.twitter_version }}-sideloaded
          release_name: v${{ github.event.inputs.twitter_version }}-sideloaded - BHTwitter
          draft: true
          prerelease: true
          body: |
            **Release Notes**

            - Build Option: Sideloaded
            - Twitter Version: ${{ github.event.inputs.twitter_version }}
            - Date: ${{ github.event.date }}

            - Built using BHTwitter project.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        if: ${{ github.event.inputs.create_release }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: main/packages/BHTwitter-sideloaded.ipa
          asset_name: BHTwitter-sideloaded.ipa
          asset_content_type: application/octet-stream
