name: Build and Release BHTwitter

on:
  workflow_dispatch:
    inputs:
      decrypted_twitter_url:
        description: "The direct URL to the decrypted Twitter ipa"
        default: ""
        required: true
        type: string
      commit_id:
        description: "(Optional) Commit ID to build at"
        default: ""
        required: false
        type: string
      create_release:
        description: "Create a draft release"
        default: true
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build BHTwitter
    runs-on: macos-12
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.6
        with:
          path: main
          ref: ${{ github.event.inputs.commit_id || github.ref }}
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Setup Theos
        uses: actions/checkout@v4.1.6
        with:
          repository: theos/theos
          ref: 3da31488281ecf4394d10302d2629607f4a1aa07
          path: theos
          submodules: recursive

      - name: Caching
        id: SDK
        uses: actions/cache@v4.0.2
        env:
          cache-name: iOS-16.4-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}

      - name: Download iOS 16.4 SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          git clone -n --depth=1 --filter=tree:0 https://github.com/arichorn/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.4.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.1.6
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive
        
      - name: Set PATH environment variable
        run: echo "export PATH=\$PATH:${{ github.workspace }}/theos:${{ github.workspace }}/theos-jailed" >> ~/.bash_profile

      - name: Export decrypted twitter ipa
        run: |
          cd main
          mkdir -p packages
          curl "${{ github.event.inputs.decrypted_twitter_url }}" -o packages/com.atebits.Tweetie2.ipa
          ls -lh packages
          ls -lh packages/com.atebits.Tweetie2.ipa

      - name: Build and Package
        run: |
          cd main
          export THEOS=/Users/runner/work/theos
          export PATH=$THEOS/bin:$PATH
          chmod +x build.sh
          ./build.sh --sideloaded
